---
driver:
  name: vagrant
  provider: virtualbox
  memory: 2048
  cpus: 2
  network:
    - ["forwarded_port", {guest: 25565, host: 25565, protocol: "tcp"}]
    - ["forwarded_port", {guest: 19132, host: 19132, protocol: "udp"}]

verifier:
  name: inspec
  sudo_path: true

# see https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md for options
provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: all
  ansible_connection: ssh
  require_windows_support: true
  ansible_host_key_checking: false
  ansible_verbose: true
  playbook: minecraft-server.yml
  additional_copy_path: ['test_fixtures']
  extra_vars: {}

platforms:
  - name: ubuntu-18.04
    driver:
      box: bento/ubuntu-18.04

suites:
  - name: minecraft-server-default
    provisioner:
      extra_vars: {}
    verifier:
      inspec_tests:
        - test/integration/default
  - name: minecraft-server-vanilla-with-existing-world
    provisioner:
      extra_vars: { minecraft_level_source_url: 'file:///tmp/kitchen/test_fixtures/DefaultMinecraftVanillaWorld_Backup-2020_07_18_13-29.zip', enable_minecraft_server: True, enable_bedrock_server: True}
    verifier:
      inspec_tests:
        - test/integration/default
  - name: minecraft-server-vanilla-with-s3
    provisioner:
      extra_vars: { s3_bucket_url: 's3_bucket_url', enable_minecraft_server: True, enable_bedrock_server: True}
    verifier:
      inspec_tests:
        - test/integration/default
