---
driver:
  name: vagrant
  provider: virtualbox
  memory: 2048
  cpus: 2
  network:
    - ["forwarded_port", {guest: 25565, host: 25565, protocol: "tcp"}]
    - ["forwarded_port", {guest: 19132, host: 19132, protocol: "udp"}]

verifier:
  name: inspec
  sudo_path: true

provisioner:
  name: ansible_playbook
  roles_path: roles
  hosts: all
  ansible_connection: ssh
  require_windows_support: true
  ansible_host_key_checking: false
  ansible_verbose: true
  playbook: minecraft-server.yml
  extra_vars: {}

platforms:
  - name: ubuntu-18.04
    driver:
      box: bento/ubuntu-18.04

suites:
  - name: minecraft-server-default
    provisioner:
      extra_vars: {}
    verifier:
      inspec_tests:
        - test/integration/default
  - name: minecraft-server-vanilla-with-aws-s3
    provisioner:
      extra_vars: { minecraft_level_source_url: '', enable_minecraft_server: True, enable_bedrock_server: True}
    verifier:
      inspec_tests:
        - test/integration/default
