---
- name: Minecraft server
  hosts: all
  vars: 
    minecraft_user: minecraft
    minecraft_group: "{{ minecraft_user }}"
    minecraft_home: /opt/minecraftserver
    minecraft_server_dir: "{{ minecraft_home }}/minecraft"
    enable_minecraft_server: True
    enable_bedrock_server: True
    supported_ansible_os_families:
      - Debian
  tasks:
    - name: check for supported OS
      assert:
        that:
          - "ansible_os_family in supported_ansible_os_families"

    - name: Run common tasks
      include_role:
        name: common

    - name: Vanilla minecraft server
      include_role:
        name: vanilla_minecraft
      when: "enable_minecraft_server == True"

    - name: Bedrock minecraft server
      include_role:
        name: bedrock
      when: "enable_bedrock_server == True"
...