---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  become: yes

- name: Get required packages
  apt: 
    name: "{{ required_packages }}"
    state: present
    update_cache: yes
  become: yes

- name: Get optional packages
  apt: 
    name: "{{ optional_packages }}"
    state: present
  become: yes

- name: Ensure Minecraft user group exists
  group:
    name: "{{ minecraft_group }}"
    state: present
    system: yes
  become: yes

- name: Ensure the Minecraft user exists
  user:
    name: "{{ minecraft_user }}"
    comment: The minecraft user.
    group: "{{ minecraft_group }}"
    home: "{{ minecraft_home }}"
    system: yes
  become: yes
...